// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB3HXbazt4an-ufqlQCH5Yz9MUU61Io7Jo',
    appId: '1:1095321927299:ios:99e1a119a838ca5ee765b6',
    messagingSenderId: '1095321927299',
    projectId: 'my-expenses-tracker-app',
    storageBucket: 'my-expenses-tracker-app.firebasestorage.app',
    iosBundleId: 'com.example.expensesApp',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB3HXbazt4an-ufqlQCH5Yz9MUU61Io7Jo',
    appId: '1:1095321927299:ios:99e1a119a838ca5ee765b6',
    messagingSenderId: '1095321927299',
    projectId: 'my-expenses-tracker-app',
    storageBucket: 'my-expenses-tracker-app.firebasestorage.app',
    iosBundleId: 'com.example.expensesApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBpuB4TviwcAu_75ukR-RKFOTG0EWx9q2M',
    appId: '1:1095321927299:web:bb834195f4a46f8ae765b6',
    messagingSenderId: '1095321927299',
    projectId: 'my-expenses-tracker-app',
    authDomain: 'my-expenses-tracker-app.firebaseapp.com',
    storageBucket: 'my-expenses-tracker-app.firebasestorage.app',
    measurementId: 'G-RMWTLCT84D',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBpuB4TviwcAu_75ukR-RKFOTG0EWx9q2M',
    appId: '1:1095321927299:web:bb834195f4a46f8ae765b6',
    messagingSenderId: '1095321927299',
    projectId: 'my-expenses-tracker-app',
    authDomain: 'my-expenses-tracker-app.firebaseapp.com',
    storageBucket: 'my-expenses-tracker-app.firebasestorage.app',
    measurementId: 'G-RMWTLCT84D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAlpuRSy98CXOUmtjY2kFQ0YkZSL61OYU4',
    appId: '1:1095321927299:android:eab4bb3d76538fd2e765b6',
    messagingSenderId: '1095321927299',
    projectId: 'my-expenses-tracker-app',
    storageBucket: 'my-expenses-tracker-app.firebasestorage.app',
  );

}